services:

  nginx:
    image: nginx
    container_name: ${APP_NAME}-nginx
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST_DEFAULT}
    depends_on:
      - php
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../app/:/var/www/html/
    networks:
      frontend:
        aliases:
          - ${VIRTUAL_HOST_DEFAULT}
      backend:

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
      args:
        GIT_USER_NAME: ${GIT_USER_NAME}
        GIT_USER_EMAIL: ${GIT_USER_EMAIL}
        GIT_CORE_EDITOR: ${GIT_CORE_EDITOR}
    container_name: ${APP_NAME}-php
    volumes:
      - ../app/:/var/www/html/
      - ~/.ssh:/root/.ssh:ro
    networks:
      - frontend
      - backend

  mysql:
    image: mysql
    container_name: ${APP_NAME}-mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_EXTERNAL_PORT}:3306"
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}-phpmyadmin
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST_PHPMYADMIN}
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - frontend
      - backend

networks:
  frontend:
    name: proxy_proxy
    external: true
  backend:
